version: 0.0
os: linux
files:
  - source: /forgather-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/forgather-backend
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/forgather-backend
    owner: ubuntu
    group: ubuntu
    mode: "755"
    type:
      - directory
  - object: /home/ubuntu/forgather-backend/forgather-0.0.1-SNAPSHOT.jar
    owner: ubuntu
    group: ubuntu
    mode: "644"
    type:
      - file
hooks:
  AfterInstall:
    - location: /deploy.sh
      timeout: 180
      runas: root
